#!/bin/sh

##
# HubSpot API emails download
#
# Syntax:
#
#     hubspot-api-emails-download
#
# This tool is for [HubSpot](https://hubspot.com) account users.
# This tool connects to the HubSpot API and downloads emails.
#
# The output is a series of JSON files with file names that
# show the offset number and the requested record count limit.
#
# Example output file names:
#
#     emails-offset-0-limit-300.json
#     emails-offset-300-limit-300.json
#     emails-offset-600-limit-300.json
#
# This tool also combines the files' emails into one file name:
#
#     emails.json
#
# Author: joel@joelparkerhenderson.com
##

set -euf

# Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

##
#
# HubSpot API
#
##

# Get HubSpot API URI to download
# Syntax: uri $offset $limit
uri() {
    echo "https://api.hubapi.com/marketing-emails/v1/emails?hapikey=$HUBSPOT_API_KEY&offset=$offset&limit=$limit"
}

# Get name to save the data file
# Syntax: file_name $offset $limit
file_name() {
    echo "emails-offset-$offset-limit-$limit.json"
}

# Get the number of JSON email items in a file
# Syntax: file_objects_length $file_name
file_objects_length() {
    jq '.objects | length' "$1"
}

# Combine all the response contacts files into one big file
# Syntax: file_join
file_join() {
    jq -s 'reduce .[].objects as $item ([]; . + $item)' emails-offset-*-limit-*.json > emails.json
}

# Verify preflight
# Syntax: preflight
preflight() {
    [ -z ${HUBSPOT_API_KEY+x} ] && die "Environment needed: HUBSPOT_API_KEY"
    command_exists_or_die curl
    command_exists_or_die jq
}

# Main function
# Syntax: main
main() {
    offset=0
    limit=300
    while true; do
        file_name=$(file_name $offset $limit)
        test -e "$file_name" || curl -s $(uri $offset $limit) > "$file_name"
        length=$(file_objects_length "$file_name")
        if [ "$length" != "$limit" ]; then
            break
        fi
        offset=$(( $offset + $limit ))
    done
    file_join
}

preflight
main
exit 0
